Website/Project/users/views.py
from flask import flash,render_template,url_for,Blueprint,redirect,request,session,logging,jsonify
from flask_login import current_user,login_user,logout_user,login_required, login_manager,UserMixin
from Project import app,db,mail,loginmanager
from Project.users.forms import LoginForm,RegisterForm,ResetRequestForm,PasswordResetForm,UpdateInfo,ChangePassword
from flask_mail import Message
from Project.models import User,Activity
import os
from mutagen.mp3 import MP3
import werkzeug
from werkzeug.utils import secure_filename
import soundfile as sf
import re
import stripe
from datetime import datetime,timedelta
import pathlib

users = Blueprint('users',__name__)
 
public = "pk_test_51HCJdAAB0pdFbVf1g2Lpev1JuHAkKSTLnJZWAJNvjcWFKXd806BRonbAilLwjMWikccDHPD67Sd1Olk9HTSbPxfK00iwPffxJP"
secret = "sk_test_51HCJdAAB0pdFbVf1JVaOwD2N7fuV1xWEAxARMRxKzPfZkgM414AgFAY7rgPekI9X0OrOf1ZGkGkeksPaAOh3shBl00ZLIaSpdq"

stripe.api_key = secret

@users.route('/register',methods=['GET','POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit(): #takes the information only when the all the validators are satisfied on submit
        user = User(
            name=form.name.data, 
            email=form.email.data,
            number=form.number.data,
            password = form.password.data,
            time_left= 10,
            words_left= 180
        )
        db.session.add(user)
        db.session.commit()  # Create new user
        print ('user added successfully')
        login_user(user)  # Log in as newly created user
        global userid
        userid = current_user.id
        next = request.args.get('next')
        if next == None or not next[0] == '/':
            next = url_for('users.index')
        return redirect(next)
    return render_template('register.html',form=form)


@users.route('/login',methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.index'))
        
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(password=form.password.data):
            login_user(user) 
            global userid
            userid = current_user.id
            if user.account_type == 'admin':
                return redirect('/admin')
            else:
                return redirect(url_for('users.index'))
        else:
            flash('Incorrect email or password.')
    return render_template('login.html',form=form)


@loginmanager.user_loader
def load_user(uid):
    # Check if user is logged-in on every page load.
    if uid is not None:
        return User.query.get(uid)
    return None


@loginmanager.unauthorized_handler
def unauthorized():
    # """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('users.login'))

@users.route('/logout',methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('core.index'))

@users.route('/welcome')
def index():
    try:
        user = User.query.get(userid)
    except:
        logout_user()
        return redirect(url_for('users.login'))
    time = datetime.now()
    if (time - user.subscription_time) > timedelta(days=30):
        user.membership = 'FREE'
        db.session.commit()
    return render_template('welcome.html',user=user)


@users.route('/tts')
def tts():
    return render_template('tts.html')
    

@users.route('/transcribe')
def transcribe():
    return render_template('transcribe.html',error=False)


@users.route('/emotions')
def emotions():
    return render_template('emotions.html',error=False)

def send_reset_mail(user):
    token = user.get_reset_token()
    msg = Message("Password Reset Request",sender= 'admin@anubhooti.com',recipients=[user.email])
    msg.body = f"To reset password visit following site\n\n{url_for('users.reset_password',token=token,_external=True)}\n\nIf you did not send request to reset password, simply ignore this message.\nRegards\nAnubhooti Solutions"
    mail.send(msg)

@users.route('/reset_request',methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('users.index'))
    form = ResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_mail(user)
        flash(f"Password reset email sent to {user.email}",'info')
    return render_template('reset_request.html',form=form)

@users.route('/reset/<token>',methods=['GET','POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.index'))
    user = User.verify_token(token)
    if user is None:
        flash("Token invalid or expired.",'warning')
        return redirect(url_for('users.reset_request'))
    
    form = PasswordResetForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash("Password changed successfully. Login to continue.",'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html',form=form)


@users.route('/upload',methods=['POST'])
def upload():
    if request.method == 'POST':
        file = request.files['myFile']
        my_path = str(pathlib.Path().absolute()) + '\\upload_folder'

        mylist = os.listdir(my_path) # dir
        number_files = len(mylist)
        number_files = str(number_files+1)
        filename = "\\audio_" + str(userid)+number_files + "_" + file.filename 
        create_file = filename

        print("Hiiii" + create_file)
        print(my_path)


        #file.save(my_path, secure_filename(filename))
        
        a,b = os.path.splitext(filename)
        user = User.query.get(userid)
        if(b=='.mp3'):
            audio = MP3(file)
            duration = (audio.info.length)/60   #in mins
        else:
            f = sf.SoundFile(file)
            duration = (len(f)/f.samplerate)/60 #in mins
        
        if(user.membership=='Individual'):
            if(duration>user.time_left):
                return redirect(url_for('users.subscribe'))
            else:
                #API call Speech Transcription
                
                act = Activity(
                    time = datetime.now(),
                    activity = 'Speech Transcription',
                    user_id = userid,
                    input = str(pathlib.Path().absolute()) + '\\upload_folder' + create_file,
                    output = 'hi'
                )
                db.session.add(act)
                db.session.commit()

                user.time_left = round(user.time_left-duration,2)
                db.session.commit()
                file.save(os.path.join(my_path, secure_filename(filename)))
                print("Upload Successful!")
                return render_template('transcribe.html',error=False)

        elif(user.membership=='Institutional'):
            if(duration>user.time_left):
                return redirect(url_for('users.subscribe'))
            else:
                #API call Speech Transcription
                act = Activity(
                    time = datetime.now(),
                    activity = 'Speech Transcription',
                    user_id = userid,
                    input = str(pathlib.Path().absolute()) + '\\upload_folder' + create_file,
                    output = 'hi'
                )
                db.session.add(act)
                db.session.commit()

                user.time_left = round(user.time_left-duration,2)
                db.session.commit()
                file.save(os.path.join(my_path, secure_filename(filename)))
                print("Upload Successful!")
                return render_template('transcribe.html',error=False)
        else:
            if(duration>user.time_left):
                return redirect(url_for('users.subscribe'))
            else:
                #API call Speech Transcription
                act = Activity(
                    time = datetime.now(),
                    activity = 'Speech Transcription',
                    user_id = userid,
                    input = str(pathlib.Path().absolute()) + '\\upload_folder' + create_file,
                    output = 'hi'
                )
                db.session.add(act)
                db.session.commit()
                
                user.time_left = round(user.time_left-duration,2)
                db.session.commit()
                file.save(os.path.join(my_path, secure_filename(filename)))
                print("Upload Successful!")
                return render_template('transcribe.html',error=False)
    else:
        print("Try Again!")
        return render_template('transcribe.html',error=True)


@users.route('/uploademo',methods=['POST'])
def uploademo():    
    if request.method == 'POST':
        file = request.files['myFile']
        my_path = str(pathlib.Path().absolute()) + '\\upload_folder'

        mylist = os.listdir(my_path) # dir
        number_files = len(mylist)
        number_files = str(number_files+1)
        filename = "\\audio_" + str(userid)+number_files + "_" + file.filename 
        create_file = filename

        print("Hiiii" + create_file)
        print(my_path)


        #file.save(my_path, secure_filename(filename))
        
        a,b = os.path.splitext(filename)
        user = User.query.get(userid)
        if(b=='.mp3'):
            audio = MP3(file)
            duration = (audio.info.length)/60   #in mins
        else:
            f = sf.SoundFile(file)
            duration = (len(f)/f.samplerate)/60 #in mins
        
        if(user.membership=='Individual'):
            if(duration>user.time_left):
                return redirect(url_for('users.subscribe'))
            else:
                #API call Speech Transcription
                
                act = Activity(

Website/Project/templates/about.html
{% extends 'base.html' %}
{% block content %}
<style>
    .box{
        border: none;
        border-bottom: 1px solid black;
        background: transparent;
    }
    .box:focus{
        border: none;
        border-bottom: 1px solid #325ee4;
        outline: none;
    }
</style>
<form method="POST">
    {{form.hidden_tag()}}
    <div class="row m-4">
        <label for="#name" class="mt-1 col-sm-1 mr-3">Name</label>
        <div id="name" class=col-md>{{form.name(class="box",style="width:15rem;")}}</div>
    </div>
    <div class="row m-4">
        <label for="#num" class="mt-1 col-sm-1 mr-3">Number</label>
        <div id="num" class="col-md">{{form.number(class="box",style="width:15rem;")}}</div>
    </div>
    {{form.submit(class="btn btn-md btn-outline-primary ml-4 mt-4")}}
    {% if success %}
    <div class="alert alert-success" style="width:18rem;margin-top:3rem;margin-left:3rem;">
        Information changed successfully!
    </div>
    {% endif %}
</form>
{% endblock %}

Website/Project/templates/activity.html
{% extends 'base.html' %}
{% block content %}
  {% if acts %}
    {% for act in acts %}      
      <div class="card my-1">
        <h6 class="card-header">{{act.activity}}</h6>
        <div class="card-body">
          <p>{{ act.time.strftime('%d-%m-%Y')}}</p>
          <p>{{ act.time.strftime('%H:%M %p')}}</p>
          <hr>
          <p>Input</p>
          <p>Output</p>
        </div>
      </div>
    {% endfor %}
  {% else %}
  <h3 class="mt-4 ml-4">No previous activity</h3>
  {% endif %}
{% endblock %}

Website/Project/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Blank Page - Anubhooti Solutions</title>
    <link rel="stylesheet" href="{{url_for('static',filename='bootstrap.min.css')}}">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>
        
    </style>
</head>

<body id="page-top">
    <div id="wrapper">
        <nav class="navbar navbar-dark align-items-start sidebar sidebar-dark accordion p-0" style="background-color:  #0b8abc;" >
            <div class="container-fluid d-flex flex-column p-0">
                <a href="{{url_for('users.index')}}"><img class="col mt-3" src="{{url_for('static',filename='assets/img/logo.png')}}" style="height:2rem;width:4rem;"></a>
                <hr class="sidebar-divider my-0">
                <ul class="nav navbar-nav text-light" style="margin-top:3rem;" id="accordionSidebar">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('users.index')}}"><i class="fas fa-home fa-sm fa-fw mr-2 text-gray-400"></i><span>Home</span></a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('users.tts')}}"><i class="fas fa-volume-up fa-sm fa-fw mr-2 text-gray-400"></i><span>Text-To-Speech</span></a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('users.transcribe')}}"><i class="fas fa-file-text fa-sm fa-fw mr-2 text-gray-400"></i><span>Transcribe Speech</span></a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('users.emotions')}}"><i class="fas fa-smile fa-sm fa-fw mr-2 text-gray-400"></i><span>Emotion Detection</span></a></li>
                    <hr style="margin-left:1rem;margin-right:1rem;background-color:white;width:auto;">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('users.settings')}}"><i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i><span>Settings</span></a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('users.activity')}}"><i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i><span>Activity Log</span></a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{url_for('users.logout')}}"><i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i><span>Log Out</span></a></li>
                </ul>
                <div class="text-center d-none d-md-inline"><button class="btn rounded-circle border-0" id="sidebarToggle" type="button"></button></div>
            </div>
        </nav>
        <div class="d-flex flex-column" id="content-wrapper">
            <nav class="navbar" style="color:black;border-bottom: 0.5px solid black;">
                <div class="navbar-brand">
                    <div class="row">
                        <h3 class="col mt-2 mb-0" style="font-family: 'Nunito', sans-serif;height:3rem;font-size:1.5rem;">ANUBHOOTI SOLUTIONS</h3>    
                    </div>
                </div>
            </nav>
            <div id="content" class="pl-4 pt-3 pr-4">
                {% block content %}
                
                {% endblock %}
            </div>

            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="text-center my-auto copyright"><span>Copyright © Anubhooti Solutions 2020</span></div>
                </div>
            </footer>
        </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.js"></script>
    <script src="{{url_for('static',filename='theme.js')}}"></script>


</body>

</html>

Website/Project/templates/example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
    Hi upload a file
    <form method="POST" action="upload" enctype=multipart/form-data>
        <input type="file" name="myFile" id="myFile">
        <input type="submit" value="Upload">
    </form>

</body>
</html>

Website/Project/templates/pricing.html
{% extends 'index.html' %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Pricing - Anubhooti Solutions</title>
</head>
<body>
    {% block content %}
        <section class="text-center pb-5 jumbotron" style="background-color: #0f161e;border-radius:0;margin-top:0;margin-bottom:0;" id="products">
        <h2 class="mb-2 mt-5 text-white">Pricing</h2>
        <hr class="col-lg-3 bg-white mb-5" style="width:2rem;height:0.3rem;">
        <div class="row mt-5 mb-5 pt-4 pb-5">
            <div class="col-sm-4 mt-2" style="border-radius:1rem; ">
                <div class="card col mycard" style="background-color:  #bedae8;">
                    <h1 class="mt-5 mb-5">FREE</h1>
                    <h5>Basic</h5>
                    <hr style="height:0.5rem;">
                    <ul class="list-group">
                        <li style="background-color:  #bedae8;" class="list-group-item">Process upto 180 characters of text.</li>
                        <li style="background-color:  #bedae8;" class="list-group-item">Process upto 10 minutes of audio files.</li>
                    </ul>
                    <a href="#" class="btn btn-success mt-4 mb-4">Proceed</a>
                </div>
            </div>
            <div class="col-sm-4 mt-2" style="border-radius:1rem;">
                <div class="card col mycard" style="background-color:  #bedae8;">
                    <h1 class="mt-5 mb-5">₹ 1000</h1>
                    <h5>Individual</h5>
                    <hr style="height:0.5rem;">
                    <ul class="list-group">
                        <li style="background-color:  #bedae8;" class="list-group-item">Process upto 2000 words of text.</li>
                        <li style="background-color:  #bedae8;" class="list-group-item">Process upto 2 hours of audio files.</li>
                    </ul>
                    <a href="{{url_for('users.login')}}" class="btn btn-info mt-4 mb-4"><span style="color:#FFD700;margin-right:0.5rem;">♕ </span> Proceed</a>
                </div>
            </div>
            <div class="col-sm-4 mt-2" style="border-radius:1rem; ">
                <div class="card col mycard" style="background-color:  #bedae8;">
                    <h1 class="mt-5 mb-5">₹ 5000</h1>
                    <h5>Institutional</h5>
                    <hr style="height:0.5rem;">
                    <ul class="list-group">
                        <li style="background-color:  #bedae8;" class="list-group-item">Process upto 10,000 words of text.</li>
                        <li style="background-color:  #bedae8;" class="list-group-item">Process upto 10 hours of audio files.</li>
                    </ul>
                    <a href="{{url_for('users.login')}}" class="btn btn-info mt-4 mb-4"><span style="color:#FFD700;margin-right:0.5rem;">♕ </span> Proceed</a>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}
</body>
</html>

Website/Project/templates/products.html
{% extends 'index.html' %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Products - Anubhooti Solutions</title>
</head>
<body>
    {% block content %}
    <section class="text-center pb-5 jumbotron" style="background-color: #0f161e;border-radius:0;margin-bottom:0;" id="products">
        <h2 class="mb-2 mt-5 text-white">Our Products</h2>
        <hr class="col-lg-3 bg-white mb-5" style="width:2rem;height:0.3rem;">
        <div class="row text-center offset-md-1 mt-5 mb-5 pt-4 pb-5">
            <div class="card col-md-3 ml-4 mr-4 mt-2 mycard" style="background-color: #bedae8;">
                <i class="card-img-top fa fa-4x fa-volume-up mt-5 mb-3" aria-hidden="true"></i>
                <div class="card-body">
                    <h5 class="card-title mt-5 mb-4">Text-To-Speech</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="{{url_for('users.login')}}" class="btn btn-primary mt-5 mb-2">Explore<i class="fa fa-angle-right ml-2" aria-hidden="true"></i></a>
                </div>
            </div>
            <div class="card col-md-3 ml-4 mr-4 mt-2 mycard" style="background-color: #bedae8;">
                <i class="card-img-top fa fa-file-text-o fa-4x mt-5 mb-3" aria-hidden="true"></i>
                <div class="card-body">
                    <h5 class="card-title mt-5 mb-4">Speech-To-Text</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="{{url_for('users.login')}}" class="btn btn-primary mt-5 mb-2">Explore<i class="fa fa-angle-right ml-2" aria-hidden="true"></i></a>
                </div>
            </div>
            <div class="card col-md-3 ml-4 mr-4 mt-2 mycard" style="background-color: #bedae8;">
                <i class="card-img-top fa fa-4x fa-smile-o mt-5 mb-3" aria-hidden="true"></i>
                <div class="card-body">
                    <h5 class="card-title mt-5 mb-4">Emotion Detection</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="{{url_for('users.login')}}" class="btn btn-primary mt-5 mb-2">Explore<i class="fa fa-angle-right ml-2" aria-hidden="true"></i></a>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}
</body>
</html>

Website/Project/templates/register.html
{% extends 'index.html' %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>Login - Anubhooti Solutions</title>
    </head>
    <body>
        {% block content %}
        <style type='text/css'>
            .box{
                width:20rem;
                background:transparent;
                border:none;
                border-bottom: 1px solid white;
                color:white;
            }
            .box:focus{
                border: none;
                border-bottom: 1px solid #b5d9ef;
                outline: transparent;
            }
            .mybutton:hover{
                background-color:#0b8abc;
                color:white;
                border: 1px solid #0b8abc;
            }
        </style>
        {% for message in get_flashed_messages() %}
        <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
        </div>
        {% endfor %}
        <header style="height:50rem;background:url('/static/assets/img/tech2.jpg')no-repeat center center;background-size:cover;">
            <div class="container text-white text-center">
                <div class="row" style="text-align: center; display: inline;">
                    <div class="col-xl-9 mx-auto text-light mt-5">
                        <h1>Sign Up</h1>
                    </div>
                    <form action="/register" method="POST" style="text-align: center;">
                        {{ form.csrf_token }}
                        <div class="col-xl-9 mx-auto text-light mt-3">
                            {{form.name(placeholder="Name",class="box mt-3",autocomplete="off")}}
                            {% if form.name.errors %}
                                {% for error in form.name.errors %}
                                    <p style="color:red;">{{error}}</p>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="col-xl-9 mx-auto text-light mt-3">
                            {{form.email(placeholder="Email",class="box mt-3",autocomplete="off")}}
                            {% if form.email.errors %}
                                {% for error in form.email.errors %}
                                    <p style="color:red;">{{error}}</p>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="col-xl-9 mx-auto text-light mt-3">
                            {{form.number(placeholder="Contact Number",class="box mt-3",autocomplete="off",maxlength=10)}}
                            {% if form.number.errors %}
                                {% for error in form.number.errors %}
                                    <p style="color:red;">{{error}}</p>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="col-xl-9 mx-auto text-light mt-3">
                            {{form.password(placeholder="Password",class="box passbox mt-3",autocomplete="off",onmouseout="this.type='password'",onmousemover="this.type='password'")}}
                            {% if form.password.errors %}
                                {% for error in form.password.errors %}
                                    {% if error == "Passwords don't match" or error == "Password too short" %}
                                    <style>
                                        .passbox{
                                            border-bottom: 1px solid red !important;
                                        }
                                    </style>
                                    {% endif %}
                                    <p style="color:red;">{{error}}</p>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="col-xl-9 mx-auto text-light mt-3">
                            {{form.confirm_password(placeholder="Confirm Password",class="box passbox mt-3",autocomplete="off",onmouseout="this.type='password'",onmousemover="this.type='password'")}}
                            {% if form.confirm_password.errors %}
                                {% for error in form.confirm_password.errors %}
                                    <p style="color:red;">{{error}}</p>
                                {% endfor %}
                            {% endif %}
                        </div>
                        <div class="col-xl-9 mx-auto text-light mt-4">
                            {{ form.submit(class="btn btn-md btn-light mybutton") }}
                        </div>
                        <div class="col-xl-9 mx-auto text-light mt-4">
                            Already have an account?
                            <a href="/login">Log In</a>
                        </div>                       
                    </form> 
                </div>
            </div>
        </header>
        {% endblock %}
    </body>
</html>

Website/Project/templates/reset_request.html
{% extends 'index.html' %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Reset Password</title>
</head>
<body>
    {% block content %}
    <style type='text/css'>
        .box{
            width:20rem;
            background:transparent;
            border:none;
            border-bottom: 1px solid white;
            color:white;
        }
        .box:focus{
            border: none;
            border-bottom: 1px solid #b5d9ef;
            outline: transparent;
        }
    </style>
    <header style="height:50rem;background:url('/static/assets/img/tech2.jpg')no-repeat center center;background-size:cover;">
        <div class="overlay"></div>
        <div class="container text-white text-center">
            <form class="row" method="POST">
                {{form.hidden_tag()}}
                <div class="col-xl-9 mx-auto text-light mt-5">
                    <h1>Reset Password</h1>
                </div>
                <div class="col-xl-9 mx-auto text-light mt-3">
                    {{form.email(class="box m-3",placeholder="E-mail")}}
                </div>
                {% if form.errors%}
                    <div class="alert alert-danger">Please enter your E-mail</div>
                {% endif %}
                <div class="col-md-10 col-lg-8 col-xl-7 mx-auto mt-4">
                    {{form.submit(class="btn btn-md btn-outline-light")}}
                </div>
            </form>
            {% with message = (get_flashed_messages())[0] %}
                {% if message %}
                    <div class="col-md-10 col-lg-8 col-xl-7 mx-auto mt-4">
                        <p style="color:greenyellow">Instructions to change password have been sent to your email. You can close this window</p>
                    </div>
                {% endif %}
            {% endwith %}
        </div>
    </header>
    {% endblock %}
</body>
</html>

Website/Project/templates/settings.html
{% extends 'base.html' %}
{% block content %}
<ul class="list-group">
    <li class="list-group-item"><a href="{{url_for('users.about')}}" class="btn">Change Name/Phone number</a></li>
    <li class="list-group-item"><a href="{{url_for('users.password')}}" class="btn">Change Password</a></li>
</ul>
{% endblock %}

Website/Project/templates/success.html
{% extends 'base.html' %}
{% block content %}
<style>
    .listitem{
        border:0;
    }
</style>
<div class="container mb-4">
    <div class="text-center col-md-10">
        <div class="alert alert-info row" style="border-radius: 0;">
            <i class="fa fa-check-circle" style="font-size: 1.5rem;" aria-hidden="true"></i>
            <h6 class="ml-2" style="margin-top:0.11rem;">Payment successful</h6>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-7">
            <ul class="list-group" style="border:2px solid #345bcb;">
                <li class="list-group-item listitem" style="border-radius:0;border-bottom: 1px solid #345bcb;color:white;background-color:#345bcb ;">Transaction Summary: </li>
                <li class="list-group-item listitem">Ref Id: <span style="float:right;word-wrap:break-word;min-width:auto;max-width:20rem;">{{session["id"]}}</span></li>
                <li class="list-group-item listitem">Date: <span style="float:right;">{{time.strftime('%d-%m-%Y')}}</span></li>
                <li class="list-group-item listitem">Time: <span style="float:right;">{{time.strftime('%H:%M %p')}}</span></li>
            </ul>
            <ul class="list-group" style="border:2px solid #345bcb;">
                <li class="list-group-item listitem" style="border-radius:0;border-bottom: 1px solid #345bcb;color:white;background-color:#345bcb ;">Order Summary: </li>
                <li class="list-group-item listitem">Name <span style="float:right;">{{user.name}}</span></li>
                <li class="list-group-item listitem">Email<span style="float:right;">{{user.email}}</span></li>
                <li class="list-group-item listitem">Product:<span style="float:right;">{{user.membership}}</span></li>
                <li class="list-group-item listitem" style="border-top:1px solid #345bcb;">Amount:<span style="float:right;">₹{{amount}}</span></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}